contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = true
baseURL = "/"
languageCode = "en-us"
title = "Insula Digital Studio"
canonifyURLs = true
googleAnalytics= ""

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  title = "Insula Digital Studio"
  description = "Crafting Digital Experience"
  author = "Enzo Vezzaro"
  variables = "Yes"
  english = "EN"
  logo = "/img/logo.svg"
