contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = true
baseURL = "/"
languageCode = "en-us"
title = "Insula Digital Studio"
canonifyURLs = true
googleAnalytics= "UA-108384646-1"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  english = "EN"
  logo = "/img/logo.svg"
  keywords = "insula digital studio, web development, web design, digital studio"
  author = "Enzo Vezzaro"
  description = "Crafting Digital Experience"
